runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  target_throughput_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    
beta_settings:
  cloud_sql_instances: your-db-instance-connection-name